### ISSUE TITLE
Navigation enhancement

### ISSUE THREAD

**Issue by mriedo** [PotreeViewer/PotreeViewer#41]
Buttons
left button : rotation
right button : pan 
mouse wheel : zoom in – zoom out
Mouse: Double click : zoom in to clicked spot
Keyboard shortcuts
C : rendering with classification
I : rendering with intensity
A : rendering with altitude
R: rendering with RBG
Arrows : pan … as in actual first person control mode
Page up : move up
Page down : move down
Arrows + Alt : rotate around center (rotate head in first person viewing mode)
Arrows + Ctrl : move along vertical and lateral axes
Arrows + Shift : move along the horizontal plane
Home : move to home position

**Comment by monodo** [comment]
<li>C : rendering with classification => done
<li>I : rendering with intensity => done
<li>O : rendering with intensity gradient => done
<li>A : rendering with altitude => done
<li>R: rendering with RBG => done
<li>P: Octree Depth => not working
<li> Home: move to home position => done

**Comment by mriedo** [comment]
Great ! Thanks
