### ISSUE TITLE
Profile enhancement

### ISSUE THREAD

**Issue by mriedo** [PotreeViewer/PotreeViewer#42]
Profile
Draw squares for points … to improve performance ?
Draw smaller points as in sitn.ne.ch/ profile
Same functionality as in sitn.ne.ch/ profile : scale XY, export png
Problem with classification rendering of profile
Reduce transparency of the graph panel
Create a button to pan the profile parallel  (as in fugro and tscan) : arrow up and arrow down

**Comment by monodo** [comment]
<li> Draw squares for points … to improve performance ? => For point cloud plotting, svg has been replace  by canvas. Seems ok up to 150k.
<li>Draw smaller points as in sitn.ne.ch/ profile => adaptative point size is now implemented
<li>Same functionality as in sitn.ne.ch/ profile : scale XY, export png => still to be done
<li>Problem with classification rendering of profile => solved
<li>Reduce transparency of the graph panel => done
<li>Create a button to pan the profile parallel (as in fugro and tscan) : arrow up and arrow down => done

@mriedo @PotreeViewer/owners please test http://sitn.ne.ch/lidar/

**Comment by mriedo** [comment]
Draw squares for points … to improve performance ? Ok !
Draw smaller points as in sitn.ne.ch/ profile => adaptative point size is now implemented : ok
Problem with classification rendering of profile => solved : ok
Reduce transparency of the graph panel => done : ok
Create a button to pan the profile parallel (as in fugro and tscan) : arrow up and arrow down => to be done : not sure it was what I expected. I expected that the profile line would move parallel not the profile
