### ISSUE TITLE
How to start with potree viewer

### ISSUE THREAD

**Issue by shrikant-dm** [PotreeViewer/PotreeViewer#53]
As per mentioned in https://github.com/PotreeViewer/PotreeViewer#install, I have followed all the steps but it is not working fine.
Here is the screen shot for the same. Is there some other settings that I have to configure.

Here is the browser console output

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/libs/three.js/build/three.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/libs/other/BinaryHeap.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/build/js/potree.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/config/config_sitn.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/i18next/i18next.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/resources/icons/focus.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/resources/icons/flip_y_z.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/resources/icons/distance.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/resources/icons/area.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/resources/icons/angle.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/resources/icons/volume.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/resources/icons/profile.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file://PotreeViewer/static/libs/potree/resources/icons/clip_volume.png Failed to load resource: net::ERR_FILE_NOT_FOUND
21781-1753.js:1 Uncaught ReferenceError: proj4 is not defined
potreefunctions.js:339 Uncaught ReferenceError: THREE is not defined
map.js:10 Uncaught TypeError: Cannot read property 'attributionsHtml' of undefined
```

![potree_viewer](https://cloud.githubusercontent.com/assets/17467432/20387712/78a34d9c-ace7-11e6-8aba-0fa646812f11.png)

**Comment by monodo** [comment]
Looks like the paths to all resources are wrong ("Failed to load message"). Furthermore, you should move the project into the web directory of your webserver and no acess to files directly displayed in the console output.

Anyway, PotreeViewer has not been updated for a while and will most probably disappear in the coming months as most functionnalities have been merged into [potree](https://github.com/potree/potree). Next release by the end of this year will support all functionnalities that were developped in PotreeViewer.

Thus, I suggest to set up a point cloud viewer using the [PotreeConverter](https://github.com/potree/PotreeConverter) that will index your las file(s) and setup a viewer by default in one single command line !

**Comment by shrikant-dm** [comment]
Thanks for the reply. I able to set up a point cloud viewer using the PotreeConverter.

**Comment by monodo** [comment]
Cool! Is it available online ?

**Comment by shrikant-dm** [comment]
No, currently in the development phase. Will let you know once it goes live.

**Comment by monodo** [comment]
Thanks!
